version: '2'
services:
    djgod-app:
        image: djgod
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://djgod-postgresql:5432/DjGod
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    djgod-postgresql:
        extends:
            file: postgresql.yml
            service: djgod-postgresql
