version: '2'
services:
    djgod-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/DjGod/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=DjGod
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
